In [1]:
# Add the Pandas dependency
import pandas as pd
import os

# Files to load
school_data_to_load = os.path.join("Resources/schools_complete.csv")
student_data_to_load = os.path.join("Resources/students_complete.csv")

In [2]:
# Read the school data file and store it in a Pandas DataFrame
school_data_df = pd.read_csv(school_data_to_load)
school_data_df

    School ID            school_name      type  size   budget
0           0      Huang High School  District  2917  1910635
1           1   Figueroa High School  District  2949  1884411
2           2    Shelton High School   Charter  1761  1056600
3           3  Hernandez High School  District  4635  3022020
4           4    Griffin High School   Charter  1468   917500
5           5     Wilson High School   Charter  2283  1319574
6           6    Cabrera High School   Charter  1858  1081356
7           7     Bailey High School  District  4976  3124928
8           8     Holden High School   Charter   427   248087
9           9       Pena High School   Charter   962   585858
10         10     Wright High School   Charter  1800  1049400
11         11  Rodriguez High School  District  3999  2547363
12         12    Johnson High School  District  4761  3094650
13         13       Ford High School  District  2739  1763916
14         14     Thomas High School   Charter  1635  1043130

In [3]:
# Read the student data file and store it in a Pandas DataFrame
student_data_df = pd.read_csv(student_data_to_load)
student_data_df.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [4]:
# Determine if there are any missing values in school data.
school_data_df.count()
school_data_df.isnull().sum()
school_data_df.notnull().sum()

School ID      15
school_name    15
type           15
size           15
budget         15
dtype: int64

In [5]:
# Determine if there are any misssing values in the student data.
student_data_df.count()
student_data_df.isnull().sum()
student_data_df.notnull().sum()

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
dtype: int64

In [6]:
# Determine the data types for school DataFrame
school_data_df.dtypes
#school_data_df.budget.dtype

School ID      int64
school_name      str
type             str
size           int64
budget         int64
dtype: object

In [7]:
# Determine the data types for student DataFrame
student_data_df.dtypes

Student ID       int64
student_name       str
gender             str
grade              str
school_name        str
reading_score    int64
math_score       int64
dtype: object

In [8]:
# Add each prefix and suffix to remove to a list.

prefixes_suffixes = ["Dr. ", "Mr. ", "Ms. ", "Mrs. ", "Miss ", " MD", " DDS", " DVM", " PhD"]

In [9]:
# Iterate through the "prefixes_suffixes" list and replace them with an empty space, "" when it appears in the student's name

for word in prefixes_suffixes:

    student_data_df["student_name"] = student_data_df["student_name"].str.replace(word, "")

In [10]:
student_data_df.head(20)

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
7,7,Nicole Baker,F,12th,Huang High School,96,69
8,8,Michael Roth,M,10th,Huang High School,95,87
9,9,Matthew Greene,M,10th,Huang High School,96,84
10,10,Andrew Alexander,M,10th,Huang High School,90,70
11,11,Daniel Cooper,M,10th,Huang High School,78,77
12,12,Brittney Walker,F,9th,Huang High School,64,79
13,13,William Long,M,9th,Huang High School,71,79
14,14,Tammy Hebert,F,10th,Huang High School,85,67
15,15,Jordan Carson,M,11th,Huang High School,94,88
16,16,Donald Zamora,M,9th,Huang High School,88,55
17,17,Kimberly Santiago,F,9th,Huang High School,74,75
18,18,Kevin Stevens,M,9th,Huang High School,64,69
19,19,Brandi Lyons,F,9th,Huang High School,89,80

In [11]:
# Combine the data into a single dataset.
school_data_complete_df = pd.merge(student_data_df, school_data_df, on=["school_name", "school_name"])
school_data_complete_df.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

In [12]:
# Calculate the total number of students.
student_count = school_data_complete_df["Student ID"].count()
student_count

np.int64(39170)

In [13]:
# Calculate the total number of schools.
school_count = school_data_df["school_name"].count()
school_count

np.int64(15)

In [14]:
# Calculate the total number of schools
school_count_2 = school_data_complete_df["school_name"].unique()
school_count_2

<StringArray>
[    'Huang High School',  'Figueroa High School',   'Shelton High School',
 'Hernandez High School',   'Griffin High School',    'Wilson High School',
   'Cabrera High School',    'Bailey High School',    'Holden High School',
      'Pena High School',    'Wright High School', 'Rodriguez High School',
   'Johnson High School',      'Ford High School',    'Thomas High School']
Length: 15, dtype: str

In [15]:
# Calculate the total budget of the schools

total_budget = school_data_df["budget"].sum()
total_budget

np.int64(24649428)

In [16]:
# Find the average reading score.

average_reading_score = school_data_complete_df["reading_score"].mean()
average_reading_score

np.float64(81.87784018381414)

In [17]:
# Calculate the average math score

average_math_score = school_data_complete_df["math_score"].mean()
average_math_score

np.float64(78.98537145774827)

In [18]:
# Determine passing grade

passing_math = school_data_complete_df["math_score"] >= 70
passing_reading = school_data_complete_df["reading_score"] >= 70

In [19]:
# Get all the students who are passing math in a new DataFrame

passing_math = school_data_complete_df[school_data_complete_df["math_score"] >= 70]

passing_math.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635

In [20]:
# Get all the students who are passing reading in a new DataFrame

passing_reading = school_data_complete_df[school_data_complete_df["reading_score"] >= 70]

passing_reading.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635

In [21]:
# Calculate the number of students passing math
passing_math_count = passing_math["Student ID"].count()

# Calculate the number of students passing reading
passing_reading_count = passing_reading["Student ID"].count()


print(passing_math_count)
print(passing_reading_count)

29370
33610

In [22]:
# Calculate the percentage of students that passed math
passing_math_percentage = passing_math_count / float(student_count) * 100
passing_math_percentage

np.float64(74.9808526933878)

In [23]:
# Calculate the number of students that passed reading
passing_reading_percentage = passing_reading_count/ float(student_count) * 100
passing_reading_percentage

np.float64(85.80546336482001)

In [24]:
# Calculate the students who passed both math and reading.
passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70) & (school_data_complete_df["reading_score"] >= 70)]

passing_math_reading.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635

In [25]:
# Get the total number of students that passed math and reading

passing_math_reading_count = passing_math_reading["Student ID"].count()

print(passing_math_reading_count)

25528

In [26]:
# Calculate the overall passing percentage

overall_passing_percentage = passing_math_reading_count / float(student_count) * 100

overall_passing_percentage

np.float64(65.17232575950983)

In [27]:
# Adding a list of values with keys to create a new DataFrame.
district_summary_df = pd.DataFrame(
          [{"Total Schools": school_count,
          "Total Students": student_count,
          "Total Budget": total_budget,
          "Average Math Score": average_math_score,
          "Average Reading Score": average_reading_score,
          "% Passing Math": passing_math_percentage,
         "% Passing Reading": passing_reading_percentage,
        "% Overall Passing": overall_passing_percentage}])
district_summary_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,39170,24649428,78.985371,81.87784,74.980853,85.805463,65.172326

In [28]:
# Format the "Total Students" to have the comma for a thousands separator.

district_summary_df["Total Students"] = district_summary_df["Total Students"].map("{:,}".format)

district_summary_df["Total Students"]

0    39,170
Name: Total Students, dtype: str

In [29]:
# Format "Total Budget" to have the comma for a thousands separator, a decimal separator, and a "$".

district_summary_df["Total Budget"] = district_summary_df["Total Budget"].map("${:,.2f}".format)

district_summary_df["Total Budget"]

0    $24,649,428.00
Name: Total Budget, dtype: str

In [30]:
# Format the columns.
district_summary_df["Average Math Score"] = district_summary_df["Average Math Score"].map("{:.1f}".format)

district_summary_df["Average Reading Score"] = district_summary_df["Average Reading Score"].map("{:.1f}".format)

district_summary_df["% Passing Math"] = district_summary_df["% Passing Math"].map("{:.0f}".format)

district_summary_df["% Passing Reading"] = district_summary_df["% Passing Reading"].map("{:.0f}".format)

district_summary_df["% Overall Passing"] = district_summary_df["% Overall Passing"].map("{:.0f}".format)

In [ ]:
# Display the DataFrame

district_summary_df

In [ ]:
# Standard format to reorder the columns if needed.

# Reorder the columns in the order you want them to appear.
# new_column_order = ["column2", "column4", "column1"]

# Assign a new or the same DataFrame the new column order.
# df = df[new_column_order]

In [ ]:
# Reorder the columns in the order you want them to appear.
new_column_order = ["Total Schools", "Total Students", "Total Budget","Average Math Score", "Average Reading Score", "% Passing Math", "% Passing Reading", "% Overall Passing"]

# Assign district summary df the new column order.
district_summary_df = district_summary_df[new_column_order]
district_summary_df

In [ ]:
# Determine the school type.

per_school_types = school_data_df.set_index(["school_name"])["type"]

per_school_types

In [ ]:
# Add the per_school_types into a DataFrame for testing.

df = pd.DataFrame(per_school_types)

df

In [ ]:
# Calculate the total student count.

per_school_counts = school_data_df["size"]

per_school_counts

In [ ]:
# Calculate the total student count.

per_school_counts = school_data_df.set_index(["school_name"])["size"]

per_school_counts

In [ ]:
# Calculate the total student count.

per_school_counts = school_data_complete_df["school_name"].value_counts()

per_school_counts

In [ ]:
# Calculate the total school budget.

per_school_budget = school_data_df.set_index(["school_name"])["budget"]

per_school_budget

In [ ]:
# Calculate the per capita spending.

per_school_capita = per_school_budget / per_school_counts

per_school_capita

In [ ]:
# Calculate the math scores.

student_school_math = student_data_df.set_index(["school_name"])["math_score"]

student_school_math

In [ ]:
# Calculate the average math scores.

per_school_averages = school_data_complete_df.groupby(["school_name"]).mean(numeric_only=True)

per_school_averages

In [ ]:
# Calculate the average test scores.

per_school_math = school_data_complete_df.groupby(["school_name"]).mean(numeric_only=True)["math_score"]

per_school_reading = school_data_complete_df.groupby(["school_name"]).mean(numeric_only=True)["reading_score"]

In [ ]:
# Display the average math scores for each school.

per_school_math

In [ ]:
# Display the average reading scores for each school.

per_school_reading

In [ ]:
 # To get the passing percentages, we need to:
    
 # 1. Determine what is the passing grade.
 # 2. Get the number of students who passed math and reading.
 # 3. Get the students who passed math and passed reading

In [ ]:
# Calculate the passing scores by creating a filtered DataFrame.

per_school_passing_math = school_data_complete_df[(school_data_complete_df["math_score"] >= 70)]

per_school_passing_reading = school_data_complete_df[(school_data_complete_df["reading_score"] >= 70)]

In [ ]:
# Calculate the number of students passing math and passing reading by school.

per_school_passing_math = per_school_passing_math.groupby(["school_name"]).count()["student_name"]

per_school_passing_reading = per_school_passing_reading.groupby(["school_name"]).count()["student_name"]

In [ ]:
# Calculate the percentage of passing math and reading scores per school.

per_school_passing_math = per_school_passing_math / per_school_counts * 100

per_school_passing_reading = per_school_passing_reading / per_school_counts * 100

In [ ]:
# Calculate the students who passed both math and reading.

per_passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70) & (school_data_complete_df["reading_score"] >= 70)]

per_passing_math_reading.head()

In [ ]:
# Calculate the number of students who passed both math and reading.

per_passing_math_reading = per_passing_math_reading.groupby(["school_name"]).count()["student_name"]

In [ ]:
# Calculate the overall passing percentage.

per_overall_passing_percentage = per_passing_math_reading / per_school_counts * 100

In [ ]:
# Display the overall passing percentage for each school.

per_overall_passing_percentage

In [ ]:
# Adding a list of values with keys to create a new DataFrame.

per_school_summary_df = pd.DataFrame({
            "School Type": per_school_types,
            "Total Students": per_school_counts,
            "Total School Budget": per_school_budget,
            "Per Student Budget": per_school_capita,
            "Average Math Score": per_school_math,
            "Average Reading Score": per_school_reading,
            "% Passing Math": per_school_passing_math,
            "% Passing Reading": per_school_passing_reading,
            "% Overall Passing": per_overall_passing_percentage})

per_school_summary_df.head()

In [ ]:
# Format the Total School Budget and the Per Student Budget columns.

per_school_summary_df["Total School Budget"] = per_school_summary_df["Total School Budget"].map("${:,.2f}".format)

per_school_summary_df["Per Student Budget"] = per_school_summary_df["Per Student Budget"].map("${:,.2f}".format)


# Display the data frame

per_school_summary_df.head()

In [ ]:
# Sort and show top five schools.

top_schools = per_school_summary_df.sort_values(["% Overall Passing"], ascending=False)

top_schools.head()

In [ ]:
# Sort and show bottom five schools.

bottom_schools = per_school_summary_df.sort_values(["% Overall Passing"], ascending=True)

bottom_schools.head()

In [ ]:
# Create a grade level DataFrames.

ninth_graders = school_data_complete_df[(school_data_complete_df["grade"] == "9th")]

tenth_graders = school_data_complete_df[(school_data_complete_df["grade"] == "10th")]

eleventh_graders = school_data_complete_df[(school_data_complete_df["grade"] == "11th")]

twelfth_graders = school_data_complete_df[(school_data_complete_df["grade"] == "12th")]

In [ ]:
# Test the grade level DataFrames

ninth_graders.head()

In [ ]:
# Group each grade level DataFrame by the school name for the average math score.

ninth_grade_math_scores = ninth_graders.groupby(["school_name"]).mean(numeric_only=True)["math_score"]

tenth_grade_math_scores = tenth_graders.groupby(["school_name"]).mean(numeric_only=True)["math_score"]

eleventh_grade_math_scores = eleventh_graders.groupby(["school_name"]).mean(numeric_only=True)["math_score"]

twelfth_grade_math_scores = twelfth_graders.groupby(["school_name"]).mean(numeric_only=True)["math_score"]

In [ ]:
# Display the 9th grade math scores

ninth_grade_math_scores

In [ ]:
# Display the 10th grade math scores

tenth_grade_math_scores

In [ ]:
# display the 11th grade math scores

eleventh_grade_math_scores

In [ ]:
# display the 12th grade math scores 

twelfth_grade_math_scores

In [ ]:
# Group each grade level DataFrame by the school name for the average reading score.

ninth_grade_reading_scores = ninth_graders.groupby("school_name")["reading_score"].mean()

tenth_grade_reading_scores = tenth_graders.groupby("school_name")["reading_score"].mean()

eleventh_grade_reading_scores = eleventh_graders.groupby("school_name")["reading_score"].mean()

twelfth_grade_reading_scores = twelfth_graders.groupby("school_name")["reading_score"].mean()

In [ ]:
# Display the 9th grade reading scores

ninth_grade_reading_scores

In [ ]:
# display the tenth_grade_reading_scores

tenth_grade_reading_scores

In [ ]:
# display the eleventh_grade_reading_scores

eleventh_grade_reading_scores

In [ ]:
# display the twelfth_grade_reading_scores

twelfth_grade_reading_scores

In [ ]:
# Combine each grade level Series for average math scores by school into a single DataFrame.

math_scores_by_grade = pd.DataFrame({
            "9th": ninth_grade_math_scores,
            "10th": tenth_grade_math_scores,
            "11th": eleventh_grade_math_scores,
            "12th": twelfth_grade_math_scores})

math_scores_by_grade.head()

In [ ]:
# Combine each grade level Series for average reading scores by school into a single DataFrame.

reading_scores_by_grade = pd.DataFrame({
            "9th": ninth_grade_reading_scores,
            "10th": tenth_grade_reading_scores,
            "11th": eleventh_grade_reading_scores,
            "12th": twelfth_grade_reading_scores})

reading_scores_by_grade.head()

In [ ]:
 # Format each grade column.

math_scores_by_grade["9th"] = math_scores_by_grade["9th"].map("{:.1f}".format)

math_scores_by_grade["10th"] = math_scores_by_grade["10th"].map("{:.1f}".format)

math_scores_by_grade["11th"] = math_scores_by_grade["11th"].map("{:.1f}".format)

math_scores_by_grade["12th"] = math_scores_by_grade["12th"].map("{:.1f}".format)


# Make sure the columns are in the correct order.

math_scores_by_grade = math_scores_by_grade[
                ["9th", "10th", "11th", "12th"]]


# Remove the index name.

math_scores_by_grade.index.name = None


# Display the DataFrame.

math_scores_by_grade.head()

In [ ]:
 # Format each grade column.
reading_scores_by_grade["9th"] = reading_scores_by_grade["9th"].map("{:,.1f}".format)

reading_scores_by_grade["10th"] = reading_scores_by_grade["10th"].map("{:,.1f}".format)

reading_scores_by_grade["11th"] = reading_scores_by_grade["11th"].map("{:,.1f}".format)

reading_scores_by_grade["12th"] = reading_scores_by_grade["12th"].map("{:,.1f}".format)

# Make sure the columns are in the correct order.
reading_scores_by_grade = reading_scores_by_grade[
                 ["9th", "10th", "11th", "12th"]]

# Remove the index name.
reading_scores_by_grade.index.name = None

# Display the data frame.
reading_scores_by_grade.head()

In [ ]:
# Get the descriptive statistics for the per_school_capita.

per_school_capita.describe()

In [ ]:
# Cut the per_school_capita into the spending ranges.

spending_bins = [0, 585, 615, 645, 675]

pd.cut(per_school_capita, spending_bins)

In [ ]:
# Cut the per_school_capita into the spending ranges.

spending_bins = [585, 615, 645, 675]

pd.cut(per_school_capita, spending_bins)

In [ ]:
# Cut the per_school_capita into the spending ranges.

spending_bins = [0, 585, 630, 645, 675]

per_school_capita.groupby(pd.cut(per_school_capita, spending_bins)).count()

In [ ]:
# Establish the spending bins and group names.

spending_bins = [0, 585, 630, 645, 675]

group_names = ["<$586", "$586-630", "$631-645", "$646-675"]

In [ ]:
# Categorize spending based on the bins.

per_school_summary_df["Spending Ranges (Per Student)"] = pd.cut(per_school_capita, spending_bins, labels=group_names)

per_school_summary_df

In [ ]:
# Calculate averages for the desired columns.

spending_math_scores = per_school_summary_df.groupby("Spending Ranges (Per Student)")["Average Math Score"].mean()

spending_reading_scores = per_school_summary_df.groupby("Spending Ranges (Per Student)")["Average Reading Score"].mean()

spending_passing_math = per_school_summary_df.groupby("Spending Ranges (Per Student)")["% Passing Math"].mean()

spending_passing_reading = per_school_summary_df.groupby("Spending Ranges (Per Student)")["% Passing Reading"].mean()

overall_passing_spending = per_school_summary_df.groupby("Spending Ranges (Per Student)")["% Overall Passing"].mean()

In [ ]:
# display the overall passing percentage

overall_passing_spending

In [ ]:
# Assemble into DataFrame.

spending_summary_df = pd.DataFrame({
            "Average Math Score" : spending_math_scores,
            "Average Reading Score": spending_reading_scores,
            "% Passing Math": spending_passing_math,
            "% Passing Reading": spending_passing_reading,
            "% Overall Passing": overall_passing_spending})

spending_summary_df

In [ ]:
# Formatting

spending_summary_df["Average Math Score"] = spending_summary_df["Average Math Score"].map("{:.1f}".format)

spending_summary_df["Average Reading Score"] = spending_summary_df["Average Reading Score"].map("{:.1f}".format)

spending_summary_df["% Passing Math"] = spending_summary_df["% Passing Math"].map("{:.0f}".format)

spending_summary_df["% Passing Reading"] = spending_summary_df["% Passing Reading"].map("{:.0f}".format)

spending_summary_df["% Overall Passing"] = spending_summary_df["% Overall Passing"].map("{:.0f}".format)

spending_summary_df

In [ ]:
# display the school total student count per school.

per_school_counts

In [ ]:
# Establish the bins.

size_bins = [0, 999, 1999, 5000]

group_names = ["Small (<1000)", "Medium (1000-1999)", "Large (2000-5000)"]

In [ ]:
# Categorize spending based on the bins.

per_school_summary_df["School Size"] = pd.cut(per_school_summary_df["Total Students"], size_bins, labels=group_names)

per_school_summary_df.head()

In [ ]:
# Calculate averages for the desired columns.

size_math_scores = per_school_summary_df.groupby("School Size")["Average Math Score"].mean()

size_reading_scores = per_school_summary_df.groupby("School Size")["Average Reading Score"].mean()

size_passing_math = per_school_summary_df.groupby("School Size")["% Passing Math"].mean()

size_passing_reading = per_school_summary_df.groupby("School Size")["% Passing Reading"].mean()

size_overall_passing = per_school_summary_df.groupby("School Size")["% Overall Passing"].mean()

In [ ]:
# Assemble into DataFrame.

size_summary_df = pd.DataFrame({
            "Average Math Score" : size_math_scores,
            "Average Reading Score": size_reading_scores,
            "% Passing Math": size_passing_math,
            "% Passing Reading": size_passing_reading,
            "% Overall Passing": size_overall_passing})

size_summary_df

In [ ]:
# Formatting.

size_summary_df["Average Math Score"] = size_summary_df["Average Math Score"].map("{:.1f}".format)

size_summary_df["Average Reading Score"] = size_summary_df["Average Reading Score"].map("{:.1f}".format)

size_summary_df["% Passing Math"] = size_summary_df["% Passing Math"].map("{:.0f}".format)

size_summary_df["% Passing Reading"] = size_summary_df["% Passing Reading"].map("{:.0f}".format)

size_summary_df["% Overall Passing"] = size_summary_df["% Overall Passing"].map("{:.0f}".format)

size_summary_df

In [ ]:
# Check which school types fall into each spending range.
pd.crosstab(per_school_summary_df["Spending Ranges (Per Student)"],
            per_school_summary_df["School Type"])

In [ ]:
# Calculate averages by school type.

type_math_scores = per_school_summary_df.groupby("School Type")["Average Math Score"].mean()
type_reading_scores = per_school_summary_df.groupby("School Type")["Average Reading Score"].mean()
type_passing_math = per_school_summary_df.groupby("School Type")["% Passing Math"].mean()
type_passing_reading = per_school_summary_df.groupby("School Type")["% Passing Reading"].mean()
type_overall_passing = per_school_summary_df.groupby("School Type")["% Overall Passing"].mean()

# Combine into one table.
per_type_summary_df = pd.DataFrame({
    "Average Math Score": type_math_scores,
    "Average Reading Score": type_reading_scores,
    "% Passing Math": type_passing_math,
    "% Passing Reading": type_passing_reading,
    "% Overall Passing": type_overall_passing})

per_type_summary_df

In [ ]:
# Roll-up by school type.

type_student_summary = per_school_summary_df.groupby("School Type")["Total Students"].agg(
    Schools="count",
    Total_Students="sum",
    Avg_Students_Per_School="mean",
)

type_student_summary

In [ ]:
per_school_summary_df.groupby(["School Type", "Spending Ranges (Per Student)"], observed=True)["% Overall Passing"].agg(["count", "mean"])

In [ ]:
print(pd.__version__)